name: bead-spring 
channels:
  - conda-forge
dependencies:
  - foyer
  - freud
  - gmso >= 0.10.0
  - gsd
  - hoomd
  - jupyter
  - matplotlib
  - mbuild
  - mdanalysis
  - numpy
  - pip
  - pymbar
  - pytest
  - pytest-cov
  - python
  - rowan
  - signac
  - signac-flow
  - symengine
  - python-symengine
  - unyt
  - pip:
      - git+https://github.com/chrisjonesbsu/hoomd-polymers.git@add/shear
